### ISSUE TITLE
Create an enum type custom property

### ISSUE THREAD

**Issue by jonathanalvares9009** [Atri-Labs/atrilabs-engine#462]
We need to create an enum type custom property (dropdown)

**Comment by jonathanalvares9009** [comment]
## TODO

- [ ] Create a type of enum in the app-design-forest package and build it
- [ ] Understand how UI works
- [ ] Create a UI for enum type
- [ ] Test the created UI
